### ISSUE TITLE
webim 使用 accessToken 登录问题

### ISSUE THREAD

**Issue by quansenx** [easemob/web-im#3]
```js
conn.open({
    user: username,
    // pwd: password,
    appKey: appkey,
    accessToken: accessToken
  })
```

accessToken 是通过 REST API 获取到的管理员 token，在 open 的时候提示“登录失败，请输入正确的用户名和密码”。如果把 accessToken 去掉就可以登录成功，请问这是什么原因。望解答，谢谢！

**Comment by chunjin-li** [comment]
这儿要使用普通用户的uid和pwd

**Comment by quansenx** [comment]
@chunjin-li 用的就是开发者中心-我的应用-IM用户的帐号登录的

**Comment by alexgreenbar** [comment]
1. The current UI was designed for login with user/password, not for user/token
2. If you want to use user/token for login, then code like below
	var login = function() {
		var user = $("#username").val();
		if (user == '') {
			alert("请输入用户名");
			return;
		}
		hiddenLoginUI();
		showWaitLoginedUI();
		conn.open({
			apiUrl : apiURL,
			user : user,
			accessToken: 'YWMtXo2zcgXPEeWyuas4fXik1AAAAU7Tb7bSn47E0vJDLNF61r6BOCYVdXX8bLw',
			appKey : appkey
		});
		return false;
	};

And in the login dialog, only need input user name, then click login button.

3. For next step, we will improve UI to support username/token login too.

Thx,
--Alex

**Comment by alexgreenbar** [comment]
Now the demo on master support use token to login, you can give it a try.

--Alex
