### ISSUE TITLE
关闭环信时，出现一个未定义异常，引起代码中断

### ISSUE THREAD

**Issue by brotherhorse** [easemob/web-im#7]
TypeError: Cannot read property 'disconnect' of undefined
    at connection.close (easemob.im-1.0.7.js:1348)
    at Object.open (chatEasemobServices.js:229)
    at Object.login (chatServices.js:282)

**Comment by stupidkiller** [comment]
`Strophe.Websocket.prototype._closeSocket = function () { 
        var me = this;

        if ( me.socket ) {
            setTimeout(function () { 
                try {
                    me.socket.close();
                } catch ( e ) {} 
            }, 0);
        } else {
            me.socket = null;
        }    
    } `
改写strophe的_closeSocket方法试试，添加上面代码就可以了， 我本地测试可以了
