### ISSUE TITLE
项目clone下来，运行sdk中的demo.html, websdk 1.4.8 报错

### ISSUE THREAD

**Issue by JohnsonChee** [easemob/web-im#75]
换成官方文档的1.4.5版本，就跑通了，麻烦下次示例引一个可跑通的sdk

**Comment by zzfScarecrow** [comment]
刚刚特地Clone了一下，不知道您做的什么操作报错了

**Comment by JohnsonChee** [comment]
我没使用webpack去跑，而是直接在根目录起服务，去访问sdk文件夹下的demo.html，测试接口功能，然后就报错 

options.error is not a function
    at error (websdk-1.4.8.js:2083)
    at XMLHttpRequest.xhr.onreadystatechange (websdk-1.4.8.js:918)，

![image](https://cloud.githubusercontent.com/assets/12552574/22143615/9b8ffb9a-df35-11e6-87c8-3fe06adab6c1.png)
把1.4.8换成cdn上的1.4.5就跑通了

**Comment by zzfScarecrow** [comment]
您是如何直接在根目录起服务的

**Comment by JohnsonChee** [comment]
http-server ./

**Comment by zzfScarecrow** [comment]
感谢您提供的信息，我们已经修复了Bug
