### ISSUE TITLE
关于webim文档中发送图片消息问题

### ISSUE THREAD

**Issue by JohnsonChee** [easemob/web-im#76]
由于ios端接受图片消息需要提供图片的size: width 和 height，而web端的文档中并未提供这两个参数，导致ios端在收到图片消息会自动奔溃。求解决

**Comment by wk3368** [comment]
we'll fix it soon

**Comment by lizilong1989** [comment]
@JohnsonChee 2.x和3.x ios SDK都没有复现出这个问题,具体ios sdk的版本是多少?

**Comment by JohnsonChee** [comment]
@lizilong1989 ios 3.2.3

**Comment by JohnsonChee** [comment]
@wk3368 @lizilong1989 Ios工程师反应，其实是因为ios老版本兼容，不能算是sdk的锅

**Comment by JohnsonChee** [comment]
Ios工程师反应，其实是因为ios老版本不兼容，不是sdk的问题，先关闭问题了
