### ISSUE TITLE
请问为什么克隆在本地服务器上跑不起来？

### ISSUE THREAD

**Issue by longfeiling** [easemob/web-im#79]
$ npm run dev

> webim@1.4.10 dev D:\git_repository\webrtc_Demo\web-im
> cross-env NODE_ENV=develop node build/dev-server.js

D:\git_repository\webrtc_Demo\web-im
D:\git_repository\webrtc_Demo\web-im\node_modules\webpack\lib\webpack.js:19
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
                ^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (D:\git_repository\webrtc_Demo\web-im\node_modules\webpack\lib\webpack.js:19:9)
    at Object.<anonymous> (D:\git_repository\webrtc_Demo\web-im\build\dev-server.js:5:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Feeling123\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! webim@1.4.10 dev: `cross-env NODE_ENV=develop node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webim@1.4.10 dev script 'cross-env NODE_ENV=develop node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=develop node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webim
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webim
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\git_repository\webrtc_Demo\web-im\npm-debug.log

**Comment by readying** [comment]
+1

**Comment by lvlei14** [comment]
+1

**Comment by zy410419243** [comment]
+1

**Comment by zzfScarecrow** [comment]
需要切换到dev分支才可以run 起来

**Comment by zy410419243** [comment]
恕我没文化..啥叫切换到dev分支，搜也搜不到..

**Comment by lz1992** [comment]
我切换dev了 还是不行

**Comment by lz1992** [comment]
还是不行唉唉

**Comment by letian0805** [comment]
首先请上node官网下载最新版 https://nodejs.org/en/
然后执行：
npm update npm
npm update bower
npm update webpack
npm install
bower install
再执行 npm run dev

**Comment by letian0805** [comment]
首先请上node官网下载最新版 https://nodejs.org/en/
安装后执行：
git checkout dev
npm update npm
npm update webpack
npm install
npm run dev

**Comment by zzfScarecrow** [comment]
现在已经修复好了，可以在master分支上面直接npm install, npm run dev
