### ISSUE TITLE
isMultiLoginSessions:true 问题

### ISSUE THREAD

**Issue by mengyou658** [easemob/web-im#88]
设置isMultiLoginSessions:true
然后执行yarn run dev 查看demo
登录两个标签，第二个标签打开后，第一个标签则显示：你已下线
请问，怎么才能实现：支持同一账号最多8个标签页登录 的效果

**Comment by savokiss** [comment]
同求。。。用的 sdk 1.4.8，多端登录貌似不管用。。。
